### ISSUE TITLE
Github icon sometimes is not clickable

### ISSUE THREAD

**Issue by brunocroh** [brunocroh/bolhadev.chat#34]
## Description

The GitHub corner is not clickable all the time, have some issues with it.

Need to be possible, click on it in any screen width

## Video Evidence

https://github.com/brunocroh/bolhadev.chat/assets/13812512/bdbb94da-145f-4a35-990b-bf002d3688e2

**Comment by LucasJantschChitolina** [comment]
@brunocroh Can you confirm if this bug is still happening? I couldn't simulate

I also noticed that in some cases, depending on the screen size, the link to github is above the 'Get Started' button (I added a blue background to show it), giving the impression that clicking 'Get started' leads to Github.

![image](https://github.com/brunocroh/bolhadev.chat/assets/62803510/613b7bba-6245-4cf4-8dec-4a8c368f8047)

I can fix this case and also the original one if it's still happening

**Comment by brunocroh** [comment]
Hey @LucasJantschChitolina , thanks for your feedback.
Yes, this problem doesn't happen anymore, we just added a right margin, and it's fixed.
